//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 03:17:49 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://somboon.em/ex-soap-provoder", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package em.somboon.ex_soap_provoder;
